make name: 522-milestone
channels:
  - conda-forge
dependencies:
  - ucimlrepo
  - numpy
  - scikit-learn
  - python
  - pandas
  - ipykernel
  - matplotlib
  - pandera
  - click
  - pip
  - pip:
    - vegafusion
    - altair
    - vl-convert-python
    - click
    - pyarrow

