name: 522-milestone
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - python
  - ucimlrepo
  - matplotlib
  - altair-all=5.5.0
  - ipykernel
  - scikit-learn
  - pandas
  - conda-lock
